version: '3.9'

services:

  nginx:
    build: ./nginx
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/log:/var/log/nginx
      - ./nginx/uniquenetwork.io.key:/etc/ssl/private/uniquenetwork.io.key
      - ./nginx/uniquenetwork.io.pem:/etc/ssl/certs/uniquenetwork.io.pem
      - ./python_logic/ss4.py:/app/ss4.py

    ports:
#      - "8080:8080"
      - "443:443"
#    command: /bin/sh -c 'while true; do sleep 2; df -h; done'
    networks:
      - mitm_net

  mitm:
    container_name: mitm_node
    image: mitm_python
    build:
      context: ./mitm
      dockerfile: Dockerfile-mitm
    volumes:
      - ./mitm/MitmAddon.py:/mitm/MitmAddon.py
      - ./mitm/MitmV5.py:/mitm/MitmV5.py
      - ./mitm/substra.py:/mitm/substra.py
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - mitm_net
    command: /bin/sh -c '. ~/.bashrc && mitmdump --mode reverse:http://52.206.228.237:9944/ --set listen_host=mitm_node --set listen_port=8080 --set flow_detail=3'
#    command: /bin/sh -c 'while true; do sleep 2; df -h; done'

networks:
  mitm_net:
    driver: bridge
